// <auto-generated />
using System;
using CmeSim.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CmeSim.Api.Migrations
{
    [DbContext(typeof(CmeSimDbContext))]
    partial class CmeSimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cme")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CmeSim.Api.Models.BenchmarkEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BenchmarkRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DurationMs")
                        .HasColumnType("float");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkRunId");

                    b.HasIndex("RequestId");

                    b.ToTable("BenchmarkEvents", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.BenchmarkRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Architecture")
                        .HasColumnType("int");

                    b.Property<double>("AvgBrokerQueueLen")
                        .HasColumnType("float");

                    b.Property<double>("AvgLatencyMs")
                        .HasColumnType("float");

                    b.Property<double>("AvgQpuQueueLen")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DbWriteMs")
                        .HasColumnType("float");

                    b.Property<double>("DbWriteStdMs")
                        .HasColumnType("float");

                    b.Property<double>("EnqueueMs")
                        .HasColumnType("float");

                    b.Property<double>("EnqueueStdMs")
                        .HasColumnType("float");

                    b.Property<int>("FailCount")
                        .HasColumnType("int");

                    b.Property<double>("FailRate")
                        .HasColumnType("float");

                    b.Property<int>("MaxBrokerQueueLen")
                        .HasColumnType("int");

                    b.Property<int>("MaxQpuQueueLen")
                        .HasColumnType("int");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("P95LatencyMs")
                        .HasColumnType("float");

                    b.Property<double>("P99LatencyMs")
                        .HasColumnType("float");

                    b.Property<double>("PreprocessMs")
                        .HasColumnType("float");

                    b.Property<double>("PreprocessStdMs")
                        .HasColumnType("float");

                    b.Property<double>("QpuServiceMs")
                        .HasColumnType("float");

                    b.Property<double>("QpuServiceStdMs")
                        .HasColumnType("float");

                    b.Property<double>("QpuWaitMs")
                        .HasColumnType("float");

                    b.Property<double>("QpuWaitStdMs")
                        .HasColumnType("float");

                    b.Property<double>("ResponseMs")
                        .HasColumnType("float");

                    b.Property<double>("ResponseStdMs")
                        .HasColumnType("float");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int");

                    b.Property<double>("ThroughputRps")
                        .HasColumnType("float");

                    b.Property<double>("ValidateMs")
                        .HasColumnType("float");

                    b.Property<double>("ValidateStdMs")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("BenchmarkRuns", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.CmeWindowResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActionSpikeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CmeValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<bool?>("FlowLabel")
                        .HasColumnType("bit");

                    b.Property<double?>("FlowProbability")
                        .HasColumnType("float");

                    b.Property<double>("PFlow")
                        .HasColumnType("float");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShotsUsed")
                        .HasColumnType("int");

                    b.Property<string>("WindowId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActionSpikeId");

                    b.HasIndex("ComputedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("CmeWindowResults", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.Experiment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfClients")
                        .HasColumnType("int");

                    b.Property<double>("OnlineArrivalRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("TrainingArrivalRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("Experiments", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.ExperimentModelMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("ModelAvgJobDurationSec")
                        .HasColumnType("float");

                    b.Property<double>("ModelAvgLatencyMs")
                        .HasColumnType("float");

                    b.Property<double?>("ModelP95LatencyMs")
                        .HasColumnType("float");

                    b.Property<double>("ModelQpuUtilization")
                        .HasColumnType("float");

                    b.Property<double>("ModelThroughputReqPerSec")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId")
                        .IsUnique();

                    b.ToTable("ExperimentModelMetrics", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.ActionDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DefaultDifficulty")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ActionDefinitions", "cme");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "briefcase",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Work",
                            Slug = "work"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "book",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Study",
                            Slug = "study"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "palette",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Creative",
                            Slug = "creative"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "dumbbell",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Physical",
                            Slug = "physical"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "users",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Social",
                            Slug = "social"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "gamepad",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Leisure",
                            Slug = "leisure"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "brain",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Mindfulness",
                            Slug = "mindfulness"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.0,
                            Icon = "coffee",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Daily",
                            Slug = "daily"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.69999999999999996,
                            Icon = "code",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Coding",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "coding"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.59999999999999998,
                            Icon = "search",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Code Review",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "code-review"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.69999999999999996,
                            Icon = "layout",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Frontend Dev",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "frontend-dev"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.75,
                            Icon = "server",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Backend Dev",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "backend-dev"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.65000000000000002,
                            Icon = "cloud",
                            IsActive = true,
                            IsSystem = true,
                            Name = "DevOps",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "devops"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.80000000000000004,
                            Icon = "bug",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Debugging",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "debugging"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.84999999999999998,
                            Icon = "sitemap",
                            IsActive = true,
                            IsSystem = true,
                            Name = "System Design",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "system-design"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.40000000000000002,
                            Icon = "video",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Meetings",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "meetings"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.29999999999999999,
                            Icon = "mail",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Email",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "email"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.5,
                            Icon = "file-text",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Documentation",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Slug = "documentation"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.59999999999999998,
                            Icon = "book-open",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Reading (Technical)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "reading-technical"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.34999999999999998,
                            Icon = "bookmark",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Reading (General)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "reading-general"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.90000000000000002,
                            Icon = "calculator",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Math / Problem Solving",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "math"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.69999999999999996,
                            Icon = "microscope",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Research",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "research"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.45000000000000001,
                            Icon = "edit",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Note-Taking",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "note-taking"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000016"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.80000000000000004,
                            Icon = "clipboard",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Exam Prep",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "exam-prep"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000017"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.34999999999999998,
                            Icon = "presentation",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Lecture / Webinar",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "lecture"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000018"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.5,
                            Icon = "layers",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Flashcards",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Slug = "flashcards"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000019"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.59999999999999998,
                            Icon = "pen-tool",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Writing (Essays)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Slug = "writing-essays"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000020"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.55000000000000004,
                            Icon = "feather",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Writing (Creative)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Slug = "writing-creative"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000021"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.5,
                            Icon = "pencil",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Drawing / Sketching",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Slug = "drawing"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000022"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.69999999999999996,
                            Icon = "music",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Music Composition",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Slug = "music-composition"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000023"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.55000000000000004,
                            Icon = "headphones",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Music Practice",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Slug = "music-practice"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000024"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.59999999999999998,
                            Icon = "image",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Graphic Design",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Slug = "graphic-design"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000025"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.65000000000000002,
                            Icon = "film",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Video Editing",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Slug = "video-editing"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000026"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.29999999999999999,
                            Icon = "activity",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Exercise",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Slug = "exercise"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000027"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.14999999999999999,
                            Icon = "navigation",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Walking",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Slug = "walking"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000028"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.25,
                            Icon = "heart",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Yoga",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Slug = "yoga"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000029"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.14999999999999999,
                            Icon = "move",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Stretching",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Slug = "stretching"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000030"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.34999999999999998,
                            Icon = "trophy",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Sports",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Slug = "sports"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000031"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.40000000000000002,
                            Icon = "zap",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Dance",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Slug = "dance"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000032"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.40000000000000002,
                            Icon = "message-circle",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Conversation",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Slug = "conversation"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000033"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.65000000000000002,
                            Icon = "monitor",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Presentation",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Slug = "presentation"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000034"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.59999999999999998,
                            Icon = "award",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Teaching",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Slug = "teaching"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000035"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.69999999999999996,
                            Icon = "mic",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Interview",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Slug = "interview"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000036"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.29999999999999999,
                            Icon = "phone",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Phone Call",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Slug = "phone-call"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000037"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.5,
                            Icon = "users",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Group Discussion",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Slug = "group-discussion"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000038"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.59999999999999998,
                            Icon = "target",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Gaming (Strategy)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Slug = "gaming-strategy"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000039"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.45000000000000001,
                            Icon = "crosshair",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Gaming (Action)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Slug = "gaming-action"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000040"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.40000000000000002,
                            Icon = "grid",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Gaming (Cards/Board)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Slug = "gaming-cards"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000041"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.14999999999999999,
                            Icon = "play",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Watching Video",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Slug = "watching-video"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000042"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.20000000000000001,
                            Icon = "globe",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Browsing",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Slug = "browsing"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000043"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.20000000000000001,
                            Icon = "share-2",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Social Media",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Slug = "social-media"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000044"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.10000000000000001,
                            Icon = "sunset",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Meditation",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Slug = "meditation"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000045"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.10000000000000001,
                            Icon = "wind",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Breathwork",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Slug = "breathwork"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000046"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.14999999999999999,
                            Icon = "eye",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Body Scan",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Slug = "body-scan"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000047"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.050000000000000003,
                            Icon = "eye",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Resting (Eyes Open)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Slug = "resting-eyes-open"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000048"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.050000000000000003,
                            Icon = "moon",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Resting (Eyes Closed)",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Slug = "resting-eyes-closed"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000049"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.10000000000000001,
                            Icon = "utensils",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Eating",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Slug = "eating"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000050"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.20000000000000001,
                            Icon = "train",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Commuting",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Slug = "commuting"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000051"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.29999999999999999,
                            Icon = "thermometer",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Cooking",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Slug = "cooking"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000052"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultDifficulty = 0.14999999999999999,
                            Icon = "trash-2",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Cleaning",
                            ParentId = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Slug = "cleaning"
                        });
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.ActionSpike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActionDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActionDefinitionId");

                    b.HasIndex("EndTime");

                    b.HasIndex("SessionId");

                    b.HasIndex("StartTime");

                    b.ToTable("ActionSpikes", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.EegWindowFeatures", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActionSpikeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Alpha_AF7")
                        .HasColumnType("float");

                    b.Property<double>("Alpha_AF8")
                        .HasColumnType("float");

                    b.Property<double>("Alpha_TP10")
                        .HasColumnType("float");

                    b.Property<double>("Alpha_TP9")
                        .HasColumnType("float");

                    b.Property<double>("Beta_AF7")
                        .HasColumnType("float");

                    b.Property<double>("Beta_AF8")
                        .HasColumnType("float");

                    b.Property<double>("Beta_TP10")
                        .HasColumnType("float");

                    b.Property<double>("Beta_TP9")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Delta_AF7")
                        .HasColumnType("float");

                    b.Property<double>("Delta_AF8")
                        .HasColumnType("float");

                    b.Property<double>("Delta_TP10")
                        .HasColumnType("float");

                    b.Property<double>("Delta_TP9")
                        .HasColumnType("float");

                    b.Property<bool?>("FlowLabel")
                        .HasColumnType("bit");

                    b.Property<double?>("FlowProbability")
                        .HasColumnType("float");

                    b.Property<double>("Gamma_AF7")
                        .HasColumnType("float");

                    b.Property<double>("Gamma_AF8")
                        .HasColumnType("float");

                    b.Property<double>("Gamma_TP10")
                        .HasColumnType("float");

                    b.Property<double>("Gamma_TP9")
                        .HasColumnType("float");

                    b.Property<double>("Quality")
                        .HasColumnType("float");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TaskDifficulty")
                        .HasColumnType("float");

                    b.Property<double>("Theta_AF7")
                        .HasColumnType("float");

                    b.Property<double>("Theta_AF8")
                        .HasColumnType("float");

                    b.Property<double>("Theta_TP10")
                        .HasColumnType("float");

                    b.Property<double>("Theta_TP9")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("WindowId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActionSpikeId");

                    b.HasIndex("FlowLabel");

                    b.HasIndex("SessionId");

                    b.HasIndex("Timestamp");

                    b.ToTable("EegWindowFeatures", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.InferenceRequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<int>("QpuLatencyMs")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalLatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("WindowId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("InferenceRequestLogs", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.QpuInvocationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackendName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shots")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("StartedAt");

                    b.ToTable("QpuInvocationLogs", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Sessions", "cme");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            StartedAt = new DateTime(2026, 3, 27, 13, 20, 49, 632, DateTimeKind.Utc).AddTicks(8136),
                            UserId = "user001"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            StartedAt = new DateTime(2026, 3, 27, 14, 20, 49, 632, DateTimeKind.Utc).AddTicks(8146),
                            UserId = "user002"
                        });
                });

            modelBuilder.Entity("CmeSim.Api.Models.TrainingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("BestFitness")
                        .HasColumnType("float");

                    b.Property<string>("BestParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedGenerations")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveModel")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalGenerations")
                        .HasColumnType("int");

                    b.Property<int>("TotalQpuCalls")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ExperimentId");

                    b.HasIndex("Status");

                    b.ToTable("TrainingJobs", "cme");
                });

            modelBuilder.Entity("CmeSim.Api.Models.BenchmarkEvent", b =>
                {
                    b.HasOne("CmeSim.Api.Models.BenchmarkRun", "BenchmarkRun")
                        .WithMany("Events")
                        .HasForeignKey("BenchmarkRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkRun");
                });

            modelBuilder.Entity("CmeSim.Api.Models.CmeWindowResult", b =>
                {
                    b.HasOne("CmeSim.Api.Models.FlowDataset.ActionSpike", "ActionSpike")
                        .WithMany()
                        .HasForeignKey("ActionSpikeId");

                    b.HasOne("CmeSim.Api.Models.Session", "Session")
                        .WithMany("CmeResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionSpike");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CmeSim.Api.Models.ExperimentModelMetrics", b =>
                {
                    b.HasOne("CmeSim.Api.Models.Experiment", "Experiment")
                        .WithOne("ModelMetrics")
                        .HasForeignKey("CmeSim.Api.Models.ExperimentModelMetrics", "ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.ActionDefinition", b =>
                {
                    b.HasOne("CmeSim.Api.Models.FlowDataset.ActionDefinition", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.ActionSpike", b =>
                {
                    b.HasOne("CmeSim.Api.Models.FlowDataset.ActionDefinition", "ActionDefinition")
                        .WithMany()
                        .HasForeignKey("ActionDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CmeSim.Api.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionDefinition");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.EegWindowFeatures", b =>
                {
                    b.HasOne("CmeSim.Api.Models.FlowDataset.ActionSpike", "ActionSpike")
                        .WithMany("EegWindowFeatures")
                        .HasForeignKey("ActionSpikeId");

                    b.HasOne("CmeSim.Api.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionSpike");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CmeSim.Api.Models.InferenceRequestLog", b =>
                {
                    b.HasOne("CmeSim.Api.Models.Experiment", "Experiment")
                        .WithMany("InferenceRequests")
                        .HasForeignKey("ExperimentId");

                    b.HasOne("CmeSim.Api.Models.Session", "Session")
                        .WithMany("InferenceRequests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experiment");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CmeSim.Api.Models.QpuInvocationLog", b =>
                {
                    b.HasOne("CmeSim.Api.Models.Experiment", "Experiment")
                        .WithMany("QpuInvocations")
                        .HasForeignKey("ExperimentId");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("CmeSim.Api.Models.TrainingJob", b =>
                {
                    b.HasOne("CmeSim.Api.Models.Experiment", "Experiment")
                        .WithMany("TrainingJobs")
                        .HasForeignKey("ExperimentId");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("CmeSim.Api.Models.BenchmarkRun", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CmeSim.Api.Models.Experiment", b =>
                {
                    b.Navigation("InferenceRequests");

                    b.Navigation("ModelMetrics");

                    b.Navigation("QpuInvocations");

                    b.Navigation("TrainingJobs");
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.ActionDefinition", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CmeSim.Api.Models.FlowDataset.ActionSpike", b =>
                {
                    b.Navigation("EegWindowFeatures");
                });

            modelBuilder.Entity("CmeSim.Api.Models.Session", b =>
                {
                    b.Navigation("CmeResults");

                    b.Navigation("InferenceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
